services:
  saga-server:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: server/Dockerfile
    ports:
      - "8282:8282" # Map host port 8282 to container port 8282
    restart: unless-stopped
    container_name: saga-server